version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
  build:
    commands:
      - echo Installing NPM dependencies...
      - npm install -g yarn
      - yarn
      - echo Build started on `date`
      - yarn build
  # post_build:
  #   commands:
  #     - aws s3 cp --recursive ./public "s3://$DEST_BUCKET/"
