version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
  build:
    commands:
      - echo Installing NPM dependencies...
      - npm install -g yarn
      - yarn
      - yarn build
  post_build:
    commands:
      - aws s3 cp --recursive ./public "s3://xp-cypress-demo-prd/"
# artifacts:
#   files:
#     - public/*